module RendezvousSquare
  module Customer
    include Base

    extend self

    def api
      access_token = ENV.fetch("#{get_environment}_SQUARE_ACCESS_TOKEN")
      client = Base.get_square_client
      return client.customers
    end

    def find_customer(email)
      # 1. Square v45 expects the top-level keys as keywords (**params)
      # We pass the hash generated by create_email_filter as keywords
      query_params = create_email_filter(email)
      
      begin
        # In v45, we call search(query: ..., limit: ...) directly
        result = api.search(**query_params)
    
        # 2. Accessing data: v45 returns objects, not hashes.
        # result is a Square::Types::SearchCustomersResponse
        if result.customers&.any?
          # Return the ID of the first match
          return result.customers.first.id
        end
        
        nil # No customer found
        
      rescue Square::Errors::ResponseError => e
        # v45 raises errors for 4xx/5xx responses
        Rails.logger.warn "Square Customer Search Error: #{e.body['errors']}"
        nil
      end
    end
    
    def create_email_filter(email)
      # Square's SearchCustomersRequest expects these specific nested keys.
      # Note: 'fuzzy' search is usually better for email if you want to handle typos,
      # but 'exact' is safer for unique lookups.
      {
        query: {
          filter: {
            email_address: {
              exact: email # Changed to 'exact' for more reliable matching
            }
          }
        },
        limit: 1
      }
    end

    def create_customer(user)
      Rails.logger.info("Creating new Square customer: #{user.email}")
      customer_data = create_customer_object(user)
    
      begin
        # 1. Use the new method name 'create' from the SDK
        # 2. Use double splat (**) to pass the hash as keyword arguments
        result = api.create(**customer_data)
    
        # 3. Access the data via methods, not hash keys
        # result is a Square::Types::CreateCustomerResponse object
        if result.customer&.id
          return result.customer.id
        end
    
      rescue Square::Errors::ResponseError => e
        # v45 raises error objects for 4xx/5xx responses
        # Use e.body to see the errors array if needed
        Rails.logger.error "Square Customer Creation Failed: #{e.body['errors']}"
        return false
      rescue StandardError => e
        Rails.logger.error "Unexpected error in Square create_customer: #{e.message}"
        return false
      end
    end
    
    def create_customer_object(user)
      # The SDK expects these keys as the 'params' for the CreateCustomerRequest
      {
        given_name: user.first_name,
        family_name: user.last_name,
        email_address: user.email,
        address: {
          address_line_1: user.address1,
          address_line_2: user.address2,
          locality: user.city,
          administrative_district_level_1: user.state_or_province,
          postal_code: user.postal_code,
          country: iso_3166_alpha2(user.country)
        },
        # Highly recommended for create actions to prevent duplicates if the network blips
        idempotency_key: Base.idempotency_key 
      }
    end

  end
end
