services:
  nginx:
    image: nginx

    volumes:
      - ./config/nginx/staging/certs:/etc/nginx/ssl/certs
      - ./config/nginx/staging/nginx.conf:/etc/nginx/nginx.conf
      - ./rendezvous/log:/var/log/nginx

    ports:
      - 80:80
      - 443:443

    depends_on:
      - rails_app

    networks:
      - rendezvous

  rails_app:
    image: rails_image
    build:
      context: ./rendezvous
      dockerfile: ../config/docker/Dockerfile
    

    command: ["bundle","exec","rails","server", "-b", "0.0.0.0"]
    # command: sh -c "bundle exec rake assets:precompile && bundle exec rails server -b 0.0.0.0"

    environment:
      - RAILS_DEVELOPMENT_HOSTS
      - RAILS_ENV
      - RACK_ENV
      - RENDEZVOUS_FACEBOOK_APP_ID
      - RENDEZVOUS_FACEBOOK_APP_SECRET
      - RENDEZVOUS_TWITTER_CONSUMER_KEY
      - RENDEZVOUS_TWITTER_CONSUMER_SECRET
      - RENDEZVOUS_RECAPTCHA_PUBLIC_KEY
      - RENDEZVOUS_RECAPTCHA_PRIVATE_KEY
      - MAILCHIMP_API_KEY
      - RENDEZVOUS_SES_SENDING_ADDRESS
      - RENDEZVOUS_SMTP_USER
      - RENDEZVOUS_SMTP_PASSWORD
      - DEVISE_SECRET_KEY
      - SANDBOX_BRAINTREE_MERCHANT_ID
      - SANDBOX_BRAINTREE_PUBLIC_KEY
      - SANDBOX_BRAINTREE_PRIVATE_KEY
      - SANDBOX_BRAINTREE_TOKENIZATION_KEY
      - GMAIL_USER
      - GMAIL_PASS
      - RAILS_SECRET_KEY_BASE
      # - MYSQL_DATABASE
      # - MYSQL_USER
      # - MYSQL_PASSWORD
      # - MYSQL_HOST=mysql
      # - MYSQL_ROOT_PASSWORD

    ports:
      - 3000:3000

    links:
      - db

    networks:
      - rendezvous

    depends_on:
      - db

    volumes:
      - ./rendezvous:/var/www/rendezvous
      - ./.ephemeral/tmp/mysqld:/var/run/mysqld

  db:
    image: postgres:16.1-alpine
    restart: always

    ports:
      - 5432:5432

    environment:
      - POSTGRES_PASSWORD
      - POSTRES_USER
      - POSTGRES_DB
      - PGDATA=/var/lib/postgresql/data/pgdata
      # - MYSQL_DATABASE
      # - MYSQL_USER
      # - MYSQL_PASSWORD
      # - MYSQL_HOST
      # - MYSQL_ROOT_PASSWORD

    networks:
      - rendezvous

    volumes:
      - ./.ephemeral/postgres/pgdata:/var/lib/postgresql/data/pgdata
      - ./.ephemeral/postgres/initdb:/docker-entrypoint-initdb.d

networks:
  rendezvous:
    driver: bridge
