services:
  nginx:
    image: nginx

    volumes:
      - ./config/nginx/local/certs:/etc/nginx/ssl/certs
      - ./config/nginx/local/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/local/sites-available/:/etc/nginx/sites-available/
      - ./config/nginx/local/sites-enabled/:/etc/nginx/sites-enabled/
      - ./rendezvous/log:/var/log/nginx
      - ./rendezvous:/var/www/rendezvous

    ports:
      - 443:443

    depends_on:
      - rails_app

    networks:
      - rendezvous

  rails_app:
    image: rails_image
    build:
      context: ./rendezvous
      dockerfile: ../config/docker/Dockerfile
    

    command: ["bundle","exec","rails","server", "-b", "0.0.0.0"]
    # command: sh -c "bundle exec rake assets:precompile && bundle exec rails server -b 0.0.0.0"

    environment:
      - APP_DOMAIN
      - RAILS_ENV
      - RACK_ENV
      - RAILS_DEVELOPMENT_HOSTS
      - RAILS_SECRET_KEY_BASE
      - RECAPTCHA_PUBLIC_KEY
      - RECAPTCHA_PRIVATE_KEY
      - MAILCHIMP_API_KEY
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

      ## Square ##
      # Sandbox info
      - SANDBOX_SQUARE_LOCATION_ID
      - SANDBOX_SQUARE_APP_ID
      - SANDBOX_SQUARE_ACCESS_TOKEN
      - SANDBOX_SQUARE_SDK_URL

      # Production info
      - PROD_SQUARE_LOCATION_ID
      - PROD_SQUARE_APP_ID
      - PROD_SQUARE_ACCESS_TOKEN 
      - PROD_SQUARE_SDK_URL  

      ## Mail service
      - MAIL_SERVICE  

      # Mailsender mailer info 
      - MAILSENDER_SMTP_PASSWORD
      - MAILSENDER_SMTP_DOMAIN
      - MAILSENDER_SMTP_PORT
      - MAILSENDER_SMTP_USER
      - MAILSENDER_API_KEY

      # Brevo mailer info
      - BREVO_SMTP_PASSWORD
      - BREVO_SMTP_DOMAIN
      - BREVO_SMTP_PORT
      - BREVO_SMTP_USER
      - BREVO_API_KEY

      # Mail addresses
      - SITE_ADMIN_SENDING_ADDRESS
      - INFO_SENDING_ADDRESS
 

    ports:
      - 3000:3000

    links:
      - db

    networks:
      - rendezvous

    depends_on:
      - db

    volumes:
      - ./rendezvous:/var/www/rendezvous
      - ./.ephemeral/tmp/mysqld:/var/run/mysqld

  db:
    image: mysql:8.0.32
    platform: linux/amd64
    restart: always

    ports:
      - 3306:3306

    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

    networks:
      - rendezvous

    volumes:
      - ./init_data/mysql:/docker-entrypoint-initdb.d
      - ./.ephemeral/mysqld/db_data:/var/lib/mysql
      - ./.ephemeral/tmp/mysqld:/var/run/mysqld

  adminer:
    profiles: 
      - debug
    image: adminer
    restart: always
    ports:
      - 8080:8080

    networks:
      - rendezvous

    depends_on:
      - db

networks:
  rendezvous:
    driver: bridge
