services:
  rails_app:
    stdin_open: true
    tty: true
    command: bash -c "
      bundle exec rails assets:clobber &&
      yarn build &&
      yarn build:css &&
      bundle exec rails assets:precompile &&
      bundle exec rails server -b 0.0.0.0
      "

    volumes:
      - ./rendezvous:/var/www/rendezvous

  nginx:
    image: nginx

    volumes:
      - ./config/nginx/local/certs:/etc/nginx/ssl/certs
      - ./config/nginx/local/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/local/sites-available/:/etc/nginx/sites-available/
      - ./config/nginx/local/sites-enabled/:/etc/nginx/sites-enabled/
      - ./rendezvous/log:/var/log/nginx
      - ./rendezvous:/var/www/rendezvous

    ports:
      - 443:443

    depends_on:
      - rails_app

    networks:
      - rendezvous
  db:
    ports:
      - "3306:3306"
