version: '3.3'
services:
  nginx:
    image: nginx

    volumes:
      - ./config/nginx/develop/nginx.conf:/etc/nginx/nginx.conf
      - ./rendezvous:/var/www/rendezvous

    ports:
      - 8080:8080

    depends_on:
      - rails_app

    networks:
      - rendezvous

  rails_app:
    image: rails_image
    build:
      context: ./rendezvous
      dockerfile: ../config/docker/Dockerfile
    

    command: ["bundle","exec","rails","server", "-b", "0.0.0.0"]
    # command: sh -c "bundle exec rake assets:precompile && bundle exec rails server -b 0.0.0.0"

    environment:
      - RAILS_ENV
      - RACK_ENV
      - RENDEZVOUS_FACEBOOK_APP_ID
      - RENDEZVOUS_FACEBOOK_APP_SECRET
      - RENDEZVOUS_TWITTER_CONSUMER_KEY
      - RENDEZVOUS_TWITTER_CONSUMER_SECRET
      - RENDEZVOUS_RECAPTCHA_PUBLIC_KEY
      - RENDEZVOUS_RECAPTCHA_PRIVATE_KEY
      - MAILCHIMP_API_KEY
      - RENDEZVOUS_SES_SENDING_ADDRESS
      - RENDEZVOUS_SMTP_USER
      - RENDEZVOUS_SMTP_PASSWORD
      - DEVISE_SECRET_KEY
      - BRAINTREE_MERCHANT_ID
      - BRAINTREE_PUBLIC_KEY
      - BRAINTREE_PRIVATE_KEY
      - BRAINTREE_TOKENIZATION_KEY
      - GMAIL_USER
      - GMAIL_PASS
      - RAILS_SECRET_KEY_BASE
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_HOST=mysql
      - MYSQL_ALLOW_EMPTY_PASSWORD

    ports:
      - 3000:3000

    links:
      - mysql

    networks:
      - rendezvous

    depends_on:
      - mysql

    volumes:
      - ./rendezvous:/var/www/rendezvous
      - /tmp/mysqld:/var/run/mysqld

  delayed_job:
    profiles: ["with_delayed_job"]
    
    image: rails_image
    command: /var/www/rendezvous/bin/delayed_job_docker.sh
    environment:
      - RAILS_ENV
      - RACK_ENV
      - RENDEZVOUS_FACEBOOK_APP_ID
      - RENDEZVOUS_FACEBOOK_APP_SECRET
      - RENDEZVOUS_TWITTER_CONSUMER_KEY
      - RENDEZVOUS_TWITTER_CONSUMER_SECRET
      - RENDEZVOUS_RECAPTCHA_PUBLIC_KEY
      - RENDEZVOUS_RECAPTCHA_PRIVATE_KEY
      - MAILCHIMP_API_KEY
      - RENDEZVOUS_SES_SENDING_ADDRESS
      - RENDEZVOUS_SMTP_USER
      - RENDEZVOUS_SMTP_PASSWORD
      - DEVISE_SECRET_KEY
      - BRAINTREE_MERCHANT_ID
      - BRAINTREE_PUBLIC_KEY
      - BRAINTREE_PRIVATE_KEY
      - BRAINTREE_TOKENIZATION_KEY
      - GMAIL_USER
      - GMAIL_PASS
      - RAILS_SECRET_KEY_BASE
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_HOST=mysql
      - MYSQL_ALLOW_EMPTY_PASSWORD

    networks:
      - rendezvous

    links:
      - mysql

    depends_on:
      - rails_app
      - mysql

    volumes:
      - ./rendezvous:/var/www/rendezvous
      - "/tmp/mysqld:/var/run/mysqld"

  mysql:
    image: mysql:8.0.32
    platform: linux/amd64

    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_HOST
      - MYSQL_ALLOW_EMPTY_PASSWORD

    networks:
      - rendezvous

    volumes:
      - ./.ephemeral/mysqld/db_init/rendezvous_init.sql:/docker-entrypoint-initdb.d/rendezvous_init.sql"
      - ./.ephemeral/mysqld/db_data:/var/lib/mysql
      - /tmp/mysqld:/var/run/mysqld
networks:
  rendezvous:
    driver: bridge
