services:
  rails_app:
    image: ghcr.io/timmykat/rendezvous-docker:${IMAGE_TAG}
    user: "webuser:webuser"
    command: bundle exec rails server -b 0.0.0.0 -p 3000

    ports:
      - 3000:3000

    volumes:
      - ./rendezvous/public:/var/www/rendezvous/public

    environment:
      RAILS_ENV: production
      RACK_ENV: production
      SIDEKIQ_LOG_LEVEL: info

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/up"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

    networks:
      rendezvous:

  db:
    ports: []
    volumes:
      - rendezvous-docker-prod_rendezvous_prod_data:/var/lib/mysql

  sidekiq:
    environment:
      RAILS_ENV: production
      RACK_ENV: production
      SIDEKIQ_LOG_LEVEL: info

  ## New Relic services
  newrelic-infra:
    profiles: ["disabled"]
    container_name: newrelic-infra
    image: newrelic/infrastructure-bundle:latest
    cap_add:
      - SYS_PTRACE
    pid: host
    privileged: true
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./config/new_relic/mysql-config.yml:/etc/newrelic-infra/integrations.d/mysql-config.yml:ro"
    environment:
      - RAILS_ENV=production
      - NRIA_LICENSE_KEY=${NRIA_LICENSE_KEY}
      - NR_MYSQL_USER=${NR_MYSQL_USER}
      - NR_MYSQL_PASSWORD=${NR_MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    restart: unless-stopped

    networks:
      rendezvous:

volumes:
  rendezvous-docker-prod_rendezvous_prod_data:
    external: true
