services:
  db_prod:
    image: mysql:8.0.32
    platform: linux/amd64
    restart: always

    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD

    networks:
      - rendezvous_prod_network

    volumes:
      - ./config/mysql/init:/docker-entrypoint-initdb.d
      - rendezvous_prod_data:/var/lib/mysql

    ports:
      - 3306:3306

  rails_app_prod:
    build:
      context: ./rendezvous
      dockerfile: ../config/docker/Dockerfile

    command: ["bundle","exec","rails","server", "-b", "0.0.0.0"]
    # command: sh -c "bundle exec rake assets:precompile && bundle exec rails server -b 0.0.0.0"

    environment:
      - APP_DOMAIN
      - RAILS_ENV
      - RACK_ENV
      - RAILS_DEVELOPMENT_HOSTS
      - RAILS_SECRET_KEY_BASE
      - RECAPTCHA_PUBLIC_KEY
      - RECAPTCHA_PRIVATE_KEY
      - MAILCHIMP_API_KEY
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

      ## Square ##
      # Sandbox info
      - SANDBOX_SQUARE_LOCATION_ID
      - SANDBOX_SQUARE_APP_ID
      - SANDBOX_SQUARE_ACCESS_TOKEN
      - SANDBOX_SQUARE_SDK_URL

      # Production info
      - PROD_SQUARE_LOCATION_ID
      - PROD_SQUARE_APP_ID
      - PROD_SQUARE_ACCESS_TOKEN
      - PROD_SQUARE_SDK_URL

      ## Mail service
      - MAIL_SERVICE  

      # Mailsender mailer info 
      - MAILSENDER_SMTP_PASSWORD
      - MAILSENDER_SMTP_DOMAIN
      - MAILSENDER_SMTP_PORT
      - MAILSENDER_SMTP_USER
      - MAILSENDER_API_KEY

      # Brevo mailer info
      - BREVO_SMTP_PASSWORD
      - BREVO_SMTP_DOMAIN
      - BREVO_SMTP_PORT
      - BREVO_SMTP_USER
      - BREVO_API_KEY

      # Mail addresses
      - SITE_ADMIN_SENDING_ADDRESS
      - INFO_SENDING_ADDRESS

    expose:
      - 3000:3000

    networks:
      rendezvous_prod_network:
        ipv4_address: 192.168.1.100

    depends_on:
      - db_prod

    volumes:
      - ./rendezvous/:/var/www/rendezvous

  new_relic_agent:
    container_name: newrelic-infra
    image: newrelic/infrastructure:latest
    cap_add:
      - SYS_PTRACE
    pid: host
    privileged: true
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./config/new_relic/mysql-config.yml:/etc/newrelic-infra/integrations.d/mysql-config.yml:ro"
    environment:
      - NRIA_LICENSE_KEY
    restart: unless-stopped
    networks:
      - rendezvous_prod_network

volumes:
  rendezvous_prod_data:

networks:
  rendezvous_prod_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24