services:
  db_prod:
    image: mysql:8.0.32
    platform: linux/amd64
    restart: always

    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

    networks:
      - rendezvous_prod_network

    volumes:
      - ./config/mysql/init:/docker-entrypoint-initdb.d
      - rendzvous_prod_data:/var/lib/mysql
    
    ports:
      - 3306:3306

  rails_app_prod:
    build:
      context: ./rendezvous
      dockerfile: ../config/docker/Dockerfile

    command: ["bundle","exec","rails","server", "-b", "0.0.0.0"]
    # command: sh -c "bundle exec rake assets:precompile && bundle exec rails server -b 0.0.0.0"

    environment:
      - APP_DOMAIN
      - RAILS_ENV
      - RACK_ENV
      - RAILS_DEVELOPMENT_HOSTS
      - RAILS_SECRET_KEY_BASE
      - RECAPTCHA_PUBLIC_KEY
      - RECAPTCHA_PRIVATE_KEY
      - MAILCHIMP_API_KEY
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

      ## Square ##
      # Sandbox info
      - SANDBOX_SQUARE_LOCATION_ID
      - SANDBOX_SQUARE_APP_ID
      - SANDBOX_SQUARE_ACCESS_TOKEN
      - SANDBOX_SQUARE_SDK_URL

      # Production info
      - PROD_SQUARE_LOCATION_ID
      - PROD_SQUARE_APP_ID
      - PROD_SQUARE_ACCESS_TOKEN 
      - PROD_SQUARE_SDK_URL     

      # Mailer info
      - SMTP_PASSWORD
      - SMTP_DOMAIN
      - SMTP_PORT
      - SMTP_USER
      - SITE_ADMIN_SENDING_ADDRESS
      - INFO_SENDING_ADDRESS
      - BREVO_API_KEY

    expose:
      - 3000:3000

    networks:
      - rendezvous_prod_network

    depends_on:
      - db_prod

    volumes:
      - ./rendezvous/:/var/www/rendezvous

volumes:
  - rendzvous_prod_data:

networks:
  rendezvous_prod_network:
    driver: bridge