services:
  nginx:
    image: nginx

    volumes:
      - ./config/nginx/staging/certs:/etc/nginx/ssl/certs
      - ./config/nginx/staging/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/shared/sites-available/:/etc/nginx/sites-available/
      - ./config/nginx/shared/sites-available/:/etc/nginx/sites-enabled/
      - ./rendezvous/log:/var/log/nginx/staging
      - ./rendezvous:/var/www/rendezvous

    ports:
      - 80:80
      - 443:443

    networks:
      - shared_server_network
      - internal_staging

  rails_app_staging:
    image: ghcr.io/timmykat/rendezvous_rails_app
    build:
      context: ./rendezvous
      dockerfile: ../config/docker/Dockerfile
    

    command: ["bundle","exec","rails","server", "-b", "0.0.0.0"]
    # command: sh -c "bundle exec rake assets:precompile && bundle exec rails server -b 0.0.0.0"

    environment:
      - APP_DOMAIN
      - RAILS_ENV
      - RACK_ENV
      - RAILS_DEVELOPMENT_HOSTS
      - RAILS_SECRET_KEY_BASE
      - RECAPTCHA_PUBLIC_KEY
      - RECAPTCHA_PRIVATE_KEY
      - MAILCHIMP_API_KEY
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

      # Sandbox info
      - SANDBOX_BRAINTREE_MERCHANT_ID
      - SANDBOX_BRAINTREE_PUBLIC_KEY
      - SANDBOX_BRAINTREE_PRIVATE_KEY
      - SANDBOX_BRAINTREE_TOKENIZATION_KEY

      # Mailer info
      - SMTP_PASSWORD
      - SMTP_DOMAIN
      - SMTP_PORT
      - SMTP_LOGIN
      - SITE_ADMIN_SENDING_ADDRESS
      - INFO_SENDING_ADDRES
      - BREVO_API_KEY

    ports:
      - 3000:3000

    links:
      - db_staging

    networks:
      - internal_staging

    depends_on:
      - db_staging

    volumes:
      - ./rendezvous:/var/www/rendezvous
      - ./.ephemeral/tmp/mysqld:/var/run/mysqld

  db_staging:
    image: mysql:8.0.32
    platform: linux/amd64
    restart: always

    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

    networks:
      - internal_staging

    volumes:
      - ./init_data/mysql:/docker-entrypoint-initdb.d
      - ./.ephemeral/mysqld/db_data:/var/lib/mysql
      - ./.ephemeral/tmp/mysqld:/var/run/mysqld

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

    networks:
      - internal_staging

    depends_on:
      - db_staging

networks:
  internal_staging:
    driver: bridge

  shared_server_network:
    external: true
