services:

  # The nginx container serves both the production and staging environments
  nginx:
    image: nginx
    container_name: rendezvous-nginx

    volumes:
      - ./config/nginx/hostinger/certs:/etc/nginx/ssl/certs
      - ./config/nginx/hostinger/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/hostinger/sites-available:/etc/nginx/sites-available
      - ./config/nginx/hostinger/sites-enabled:/etc/nginx/sites-enabled
      - /var/log/nginx/staging:/var/log/nginx/staging
      - /var/log/nginx/prod:/var/log/nginx/prod
      - /var/www/rendezvous-docker-staging/rendezvous:/var/www/rendezvous_staging

    ports:
      - 80:80
      - 443:443

    depends_on:
      - rails_app_staging

    networks:
      - shared_server_network
      - internal_staging

  # Production services
  # db_prod:
  #   image: mysql:8.0.32
  #   restart: always

  #   environment:
  #     - MYSQL_DATABASE
  #     - MYSQL_USER
  #     - MYSQL_PASSWORD
  #     - MYSQL_ALLOW_EMPTY_PASSWORD=true

  #   networks:
  #     - internal_prod

  #   volumes:
  #     - /var/run/mysqld/init_data:/docker-entrypoint-initdb.d
  #     - /var/lib/mysql/prod:/var/lib/mysql
  #     - /var/run/mysqld/prod:/var/run/mysqld

  # rails_app_prod:
  #   image: ghcr.io/timmykat/rendezvous_rails_app

  #   command: ["bundle","exec","rails","server", "-b", "0.0.0.0"]
  #   # command: sh -c "bundle exec rake assets:precompile && bundle exec rails server -b 0.0.0.0"

  #   environment:
  #     - PROD_APP_DOMAIN
  #     - RAILS_ENV
  #     - RACK_ENV
  #     - RAILS_DEVELOPMENT_HOSTS
  #     - RAILS_SECRET_KEY_BASE
  #     - RECAPTCHA_PUBLIC_KEY
  #     - RECAPTCHA_PRIVATE_KEY
  #     - MAILCHIMP_API_KEY
  #     - MYSQL_DATABASE
  #     - MYSQL_USER
  #     - MYSQL_PASSWORD

  #     # Mailer info
  #     - SMTP_PASSWORD
  #     - SMTP_DOMAIN
  #     - SMTP_PORT
  #     - SMTP_LOGIN
  #     - SITE_ADMIN_SENDING_ADDRESS
  #     - INFO_SENDING_ADDRES
  #     - BREVO_API_KEY

  #   links:
  #     - db_prod

  #   networks:
  #     - internal_prod

  #   depends_on:
  #     - db_prod

  #   volumes:
  #     - /var/www/rendezvous-docker/rendezvous:/var/www/rendezvous_prod
  #     - /tmp/mysqld/prod:/var/run/mysqld

  # Staging services
  db_staging:
    image: mysql:8.0.32
    container_name: rendezvous-db-staging
    platform: linux/amd64
    restart: always

    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

    networks:
      - internal_staging

    volumes:
      - /init_data/mysql:/docker-entrypoint-initdb.d
      - /var/lib/mysql/staging:/var/lib/mysql
      - /var/run/mysqld/staging:/var/run/mysqld

  rails_app_staging:
    container_name: rendezvous-rails-app-staging
    image: ghcr.io/timmykat/rendezvous_rails_app

    command: ["bundle","exec","rails","server", "-b", "0.0.0.0"]
    # command: sh -c "bundle exec rake assets:precompile && bundle exec rails server -b 0.0.0.0"

    environment:
      - APP_DOMAIN
      - RAILS_ENV
      - RACK_ENV
      - RAILS_DEVELOPMENT_HOSTS
      - RAILS_SECRET_KEY_BASE
      - RECAPTCHA_PUBLIC_KEY
      - RECAPTCHA_PRIVATE_KEY
      - MAILCHIMP_API_KEY
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

      # Mailer info
      - SMTP_PASSWORD
      - SMTP_DOMAIN
      - SMTP_PORT
      - SMTP_LOGIN
      - SITE_ADMIN_SENDING_ADDRESS
      - INFO_SENDING_ADDRES
      - BREVO_API_KEY

    links:
      - db_staging

    depends_on:
      - db_staging

    volumes:
      - /var/www/rendezvous-docker-staging/rendezvous:/var/www/rendezvous_staging
      - /tmp/mysqld/staging:/var/run/mysqld

    networks:
      - internal_staging

networks:

  internal_staging:
    driver: bridge

  # Required for prod and staging to both talk to nginx
  shared_server_network:
    external: true
