default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  timeout: 5000
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  database: <%= ENV['MYSQL_DATABASE'] %>
  host: db

development:
  <<: *default

staging:
  <<: *default

production:
  <<: *default

test:
  <<: *default
  username: test_user
  password: test_password
  database: rendezvous_test
