countries:
  USA: United States
  CAN: Canada
  MEX: Mexico
  AUT: Austria
  BEL: Belgium
  HRV: Croatia
  DNK: Denmark
  FRA: France
  DEU: Germany
  IRL: Ireland
  ITA: Italy
  NLD: Netherlands
  NOR: Norway
  PRT: Portugal
  ESP: Spain
  SWE: Sweden
  CHE: Switzerland
  GBR: United Kingdom

provinces:
  - AB
  - BC
  - MB
  - NB
  - NF
  - NT
  - NS
  - 'ON'
  - PE
  - QC
  - SK
  - YT