# Pin npm packages by running ./bin/importmap
pin "application", to: "main.js"
pin "@hotwired/turbo-rails"
pin "@hotwired/stimulus"
pin "qrcode/html5"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "jquery", to: "jquery.min.js", preload: true
pin "jquery_ujs", to: "jquery_ujs.js", preload: true
pin "jquery-ui", to: "jquery-ui.min.js", preload: true
pin "rails-ujs", to: "./rails/rails-ujs.js"
pin "respond/main.js"
pin "bootstrap", to: "bootstrap/dist/js/bootstrap"
pin "rails_sortable", to: "./vendor/rails_sortable"
pin "js-cookie", to: "js-cookie/dist/js.cookie.min"
pin "tablesorter", to: "tablesorter/dist/js/jquery.tablesorter.min.js"
pin "tablesorter.widgets", to: "tablesorter/dist/js/jquery.tablesorter.widgets"
pin "dropzone", to: "dropzone/dist/dropzone-min"
pin "magnific-popup", to: "magnific-popup/dist/jquery.magnific-popup.min"
pin "lazyload/lazyload.min"
pin "cocoon", to: "@nathanvda/cocoon/cocoon"
pin "admin"
pin "main_pages"
pin "custom"
pin "pictures"
pin "registrations"
pin "purchases"
pin "user"
pin "vehicles"
