delivery_method: :smtp
use_letter_opener: false    # Overrides production delivery method
smtp_settings:
  address:               <%= ENV["SMTP_DOMAIN"] %>
  domain:                <%= ENV["APP_DOMAIN"] %>
  user_name:             <%= ENV["SMTP_USER"] %>
  password:              <%= ENV["SMTP_PASSWORD"] %>
  port:                  <%= ENV["SMTP_PORT"] %>
  authentication:        :plain
  enable_starttls_auto:  true
  ssl:                   false
  openssl_verify_mode:   'none'

inquiry_recipients:
  - wbbw67@gmail.com
  - hellman.michaela@gmail.com
  - rendezvousLLC@kinnel.warpmail.net