# config/registration.yml
fees:
  early:
    start_date: 2026-01-01
    end_date: 2026-04-30
    adult: 100
    youth: 50
    child: 0
    adult_id:
      prod: "3GMMZYDU36QAGVVCLVX4RCFS"
      sandbox: "VLTRMDE7V3GS64EYCZCZ7EAN"
    youth_id:
      prod: "KQIRK6WTO5KEUKG5QVAJPRLM"
      sandbox: "7QUHBISEJXTQLA7NPU7YCNMA"
    child_id:
      prod: "RARJ7TDBMFX7ZNPDAFWXRI6G"
      sandbox: "NHXTPJTV6WSQDSCSRPEVBWGW"
  late:
    start_date: 2026-05-01
    end_date: 2026-06-05
    adult: 120
    youth: 60
    child: 0
    adult_id:
      prod: "HUGAQG23M5DQDBAKTVCI6YC6"
      sandbox: "SNOELG6UJNCWBV7KO7BVUKEO"
    youth_id:
      prod: "KN7YC4MCRAI5XL6U3QM737OJ"
      sandbox: "UNH3HQ66RX3CTAURCKVHQPUF"
    child_id:
      prod: "ZNHUDHZ37BTCLGS42H7N53VL"
      sandbox: "IGVEZ3PK5SSIMZOEGMFW4QOS"
  on_site:
    adult_id:
      prod: "574JG7IKCODJU4PC6MTST7JE"
      sandbox: "RIYDFHFRDPFWWPTBHYP6ASFM"
    youth_id:
      prod: "FXYF45EHDGG74ZXDO5ZKVYHB"
      sandbox: "GRPZ5765H5CT2AWQUUGVGUFI"
    child_id:
      prod: "ZTX3UQTPQHEUDOCSOE3W5ZIX"
      sandbox: "NJD66LV7QYXXVUEZW45IXVF6"

suggested_donations:
    - 10
    - 25
    - 50
    - 75
    - 100