registration_window:
  open: 2026-03-01
  close: 2026-05-28
  after_rendezvous: 2026-06-16
refund_date: 2026-06-06
sunday_lunch_max: 6      # This currently has an absolute max in the DB of 8
lake_cruise_max: 6
lake_cruise_close_date: 2026-05-27
payment_methods:
  - credit card
  - check
  - cash
  - cash or check
  - no payment
transaction_types:
  - payment
  - refund

