# The following will most likely change from year to year
dates:
  day_one: June 13, 2025
  duration: 3
  refund_date: 'June 6, 2025'
registration_window:
  open: 2025-04-01
  close: 2025-06-06
  after_rendezvous: 2025-06-16
  test: true
fees:
  adult: 75
  child: 0

payment_credentials:
  sandbox:
    application_id: <%= ENV['SANDBOX_SQUARE_APP_ID'] %>
    location_id: <%= ENV['SANDBOX_SQUARE_LOCATION_ID'] %>
  production:
    application_id: <%= ENV['PROD_SQUARE_APP_ID'] %>
    location_id: <%= ENV['PROD_SQUARE_LOCATION_ID'] %>

hotel:
  name: Courtyard Marriott
  address: 11 Excelsior Ave, Saratoga Springs
  website: https://www.marriott.com/en-us/hotels/albss-courtyard-saratoga-springs/overview/
  event_rate: (FULL)
  event_rate_link: 
  event_rate_last_day: May 30
venue:
  name: Lakeside Farms
  address: 336 Schauber Road, Ballston Lake
  website: https://www.lakesidefarmscidermill.com/

chauffeurs:
 - Bill Blaufuss
 - Jon Chomitz
 - Michaela Hellman
 - Tim Kinnel

# The following should rarely change
front_page_message:
  pre_registration: Stay tuned.
  during_registration: Registration is open.
  closed_registration: Online registration is now closed, but the Rendezvous is ON!
  post_rendezvous: See you next year!
info_pages:
  - faq
  - history
  - legal_information
  - vendors
suggested_donations:
    - 10
    - 25
    - 50
    - 100
payment_methods:
  - credit card
  - check
  - cash
  - cash or check
  - no payment
registration_statuses:
  - initiated
  - in review
  - payment due
  - complete
  - updated
  - updating
  - "cancelled - settled"
  - "cancelled - needs refund"
transaction_types:
  - payment
  - refund
official_contact:
  mailing_address_array:
    - "Citroen Rendezvous, LLC"
    - "28 11th Street"
    - "Providence, RI 02906"
    - "United States"
  chief_officer: Timothy S Kinnel
  email: rendezvousLLC@kinnel.warpmail.net
  facebook: https://www.facebook.com/groups/1796592930566951/

merchandise:
  sizes:
    - S
    - M
    - L
    - XL
    - XXL
    - XXXL
    - no size
    
vehicle_marques:
  - Citroen
  - Panhard
  - Peugeot
  - Renault
  - Other
vehicle_models:
  - C2
  - Traction Avant (11)
  - Traction Avant (15)
  - 2CV (sedan)
  - 2CV (truckette)
  - Dyane
  - D (early)
  - D (late)
  - D (wagon)
  - D (Chapron)
  - SM
  - CX (series 1)
  - CX (series 2)
  - CXA
  - GS
  - GSA
  - Ami
  - Dyane
  - Mehari
  - Visa
  - XM
  - Xantia
  - C6
  - 'H-Van'
judging_categories:
  - 'C2 / Traction Avant'
  - 'ID / DS'
  - '2CV / Truckette'
  - 'SM'
  - 'CX / CXA'
  - 'Ami / Dyane / Mehari / Visa'
  - 'GS / GSA / XM / Xantia / C6 / H-Van'
  - 'Other French'
  - 'Non-French'
countries:
  USA: United States
  CAN: Canada
  MEX: Mexico
  AUT: Austria
  BEL: Belgium
  HRV: Croatia
  DNK: Denmark
  FRA: France
  DEU: Germany
  IRL: Ireland
  ITA: Italy
  NLD: Netherlands
  NOR: Norway
  PRT: Portugal
  ESP: Spain
  SWE: Sweden
  CHE: Switzerland
  GBR: United Kingdom

provinces:
  - AB
  - BC
  - MB
  - NB
  - NF
  - NT
  - NS
  - 'ON'
  - PE
  - QC
  - SK
  - YT

print_token: "bLsa1e0Kq04hinHnX7ENvE2X389rhrLy"
captcha:
  site_key: <%= ENV['RECAPTCHA_PUBLIC_KEY'] %>
  secret_key: <%= ENV['RECAPTCHA_PRIVATE_KEY'] %>
mailchimp:
  api_key: <%= ENV['RENDEZVOUS_MAILCHIMP_API_KEY'] %>
  list:
    name: Citroen Rendezvous
    list_id: 9e696fe93f

mailer:
  delivery_method: :smtp
  use_letter_opener: false    # Overrides production delivery method
  smtp_settings:
    address:               <%= ENV['SMTP_DOMAIN'] %>
    domain:                <%= ENV['APP_DOMAIN'] %>
    user_name:             <%= ENV['SMTP_USER'] %>
    password:              <%= ENV['SMTP_PASSWORD'] %>
    authentication:        :plain
    enable_starttls_auto:  true
    enable_starttls:       true
    ssl:                   true
    port:                  <%= ENV['SMTP_PORT'] %>
    openssl_verify_mode:   'none'

development:
  mailer:
    delivery_method: :letter_opener

  inquiry_recipients:
    - tim@wordsareimages.com

production:
  mailer:
    delivery_method: :letter_opener

  inquiry_recipients:
    - wbbw67@gmail.com
    - hellman.michaela@gmail.com
    - tim@wordsareimages.com

test:
  mailer:
    delivery_method: test
