# The following will most likely change from year to year
dates:
  day_one: June 13, 2025
  duration: 3
registration_window:
  open: 2025-04-01
  close: 2025-06-06
  after_rendezvous: 2025-06-16
  test: true
fees:
  adult: 80
  child: 0

hotel:
  name: Hyatt Place Saratoga Malta
  address: 20 State Farm Place, Ballston Spa, NY, 12020
  website: https://www.marriott.com/en-us/hotels/albss-courtyard-saratoga-springs/overview/
  event_rate: $189/night
  event_registration_link: https://www.hyatt.com/en-US/group-booking/ALBZS/G-CRDV
  event_registration_last_day: May 30
venue:
  name: Lakeside Farms
  address: 336 Schauber Road, Ballston Lake
  website: https://www.lakesidefarmscidermill.com/

chauffeurs:
 - Bill Blaufuss
 - Dave & Jamie Burnham
 - Jon Chomitz
 - Michaela Hellman
 - Tim Kinnel

# The following should rarely change
front_page_message:
  pre_registration: Stay tuned.
  during_registration: Registration is open.
  closed_registration: Online registration is now closed, but the Rendezvous is ON!
  post_rendezvous: See you next year!
info_pages:
  - faq
  - history
  - legal_information
  - vendors
suggested_donations:
    - 10
    - 25
    - 50
    - 100
payment_methods:
  - credit card
  - check
  - cash
  - cash or check
  - no payment
registration_statuses:
  - initiated
  - in review
  - payment due
  - complete
  - updated
  - updating
  - "cancelled - settled"
  - "cancelled - needs refund"
transaction_types:
  - payment
  - refund
official_contact:
  mailing_address_array:
    - "Citroen Rendezvous, LLC"
    - "28 11th Street"
    - "Providence, RI 02906"
    - "United States"
  chief_officer: Timothy S Kinnel
  email: rendezvousLLC@kinnel.warpmail.net
  facebook: https://www.facebook.com/groups/1796592930566951/

merchandise:
  sizes:
    - S
    - M
    - L
    - XL
    - XXL
    - XXXL
    - no size
countries:
  USA: United States
  CAN: Canada
  MEX: Mexico
  AUT: Austria
  BEL: Belgium
  HRV: Croatia
  DNK: Denmark
  FRA: France
  DEU: Germany
  IRL: Ireland
  ITA: Italy
  NLD: Netherlands
  NOR: Norway
  PRT: Portugal
  ESP: Spain
  SWE: Sweden
  CHE: Switzerland
  GBR: United Kingdom

provinces:
  - AB
  - BC
  - MB
  - NB
  - NF
  - NT
  - NS
  - 'ON'
  - PE
  - QC
  - SK
  - YT

print_token: "bLsa1e0Kq04hinHnX7ENvE2X389rhrLy"
captcha:
  site_key: <%= ENV['RECAPTCHA_PUBLIC_KEY'] %>
  secret_key: <%= ENV['RECAPTCHA_PRIVATE_KEY'] %>
mailchimp:
  api_key: <%= ENV['RENDEZVOUS_MAILCHIMP_API_KEY'] %>
  list:
    name: Citroen Rendezvous
    list_id: 9e696fe93f
    
test:
  mailer:
    delivery_method: test
