meeting_type:
  agm: Association General Meeting
  dirm: Directors' Meeting
version_status:
  approved: Approved
  pending: Pending
standard_change_type:
  major: Major
  minor: Minor
  other: Other
standard_change_status:
  approved: Approved
  proposed: Proposed
  withdrawn: Withdrawn
recaptcha:
  public_key: 6LedYO8SAAAAAPho35-jU-DHbGAPeNJVZpcsYAgi 
  private_key: 6LedYO8SAAAAAJOIj8RKirQWUOc5LF_F8jnYeei- 