migration:
  !ruby/sym base_url: http://openeffects.org
  !ruby/sym index:
              minutes:   /dokuwiki/doku.php?id=company:minutes
              standards: /dokuwiki/doku.php?id=standards:draft:ofx_image_processing_api_2
  
sanitizer:
  !ruby/sym attributes:
    !ruby/sym all:
      - class
    a:
      - title
      - target
      - href
      - type
meeting_type:
  agm: Association General Meeting
  dirm: Directors' Meeting
version_status:
  approved: Approved
  pending:  Pending
standard_change_type:
  major: Major
  minor: Minor
  other: Other
standard_change_status:
  approved:   Approved
  proposed:   Proposed
  withdrawn:  Withdrawn
  deprecated: Deprecated
recaptcha:
  public_key:   6LedYO8SAAAAAPho35-jU-DHbGAPeNJVZpcsYAgi 
  private_key:  6LedYO8SAAAAAJOIj8RKirQWUOc5LF_F8jnYeei- 