source 'https://rubygems.org'
ruby '3.2.2'

gem 'rake'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '7.1.3.2'

# Security updates
gem "actionpack", "7.1.3.2"
gem "actiontext", "7.1.3.2"
gem "activestorage", "7.1.3.2"

# For QR code generation
gem 'delayed_job_active_record'

gem 'jsbundling-rails'
gem 'cssbundling-rails'
gem 'propshaft'

# Load environment variables in development
gem 'dotenv-rails'

gem 'turbo-rails'
gem 'importmap-rails'

# The database for Active Record
gem 'mysql2', '0.5.6'
# gem 'pg', '1.5.6'

# Use haml for templates
gem 'haml-rails'

# Use Uglifier as compressor for JavaScript assets

# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'rails_sortable'

# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1'

gem 'devise', '~> 4.9'
gem 'carrierwave'
gem 'cocoon'
gem 'role_model'
gem 'daemons'
gem 'square.rb'
gem 'dkim'
gem 'simple_form', '~>5'
gem 'redcarpet'

# Monitoring
gem 'newrelic_rpm'

# QR codes
gem 'rqrcode'
gem 'mini_magick'

gem 'gibbon' # Mailchimp API

# Application server
gem 'puma', '6.4.2'

gem 'letter_opener'

group :development do
  gem 'byebug'
  gem 'pry'
  gem 'capistrano', '3.18.1'
  gem 'capistrano-rails'
  gem 'capistrano-bundler'
  gem 'capistrano-yarn'
  gem 'ed25519', '>= 1.2', '< 2.0'
  gem 'bcrypt_pbkdf', '>= 1.0', '< 2.0'
end

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_bot_rails'
  gem 'database_cleaner'
  gem 'racksh'
end

gem "terser", "~> 1.1"
