source 'https://rubygems.org'
ruby '3.1.2'

gem 'rake'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '7.0.4'
# gem 'rails', '4.2.9'

# Browserify
gem 'browserify-rails'

# Security updates
gem 'sprockets-rails', '~> 3'
gem "actionpack", "7.0.4"
# gem "actionpack", ">= 4.2.5.2"

# Load environment variables in development
gem 'dotenv-rails'

# MySQL the database for Active Record
gem 'mysql2'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'

# Use haml for templates
gem 'haml-rails'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '~> 4.2'

# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
# gem 'jquery-rails'
# gem 'jquery-ui-rails'

# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1'

gem 'devise', '~> 4.9'
gem 'bootstrap-sass', '~> 3.1'
gem 'carrierwave'
gem 'mini_magick'
gem 'cocoon'
gem 'recaptcha', require: 'recaptcha/rails'
gem 'font-awesome-sass'
gem 'role_model'
gem 'delayed_job_active_record'
gem 'daemons'
gem 'braintree'
gem 'dkim'
gem 'simple_form', '~>5'

# Pdf creation
gem 'wkhtmltopdf-binary'
gem 'wicked_pdf'

gem 'gibbon' # Mailchimp API

# Application server
gem 'puma'

group :development do
  gem 'byebug'
  gem 'pry-rails'
  gem 'capistrano'
  gem 'capistrano-rails'
  gem 'capistrano-rbenv'
  gem 'capistrano-yarn'
  gem 'capistrano3-puma', github: "timmykat/capistrano-puma", branch: "amazon-linux-support"
end

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_bot'
  gem 'database_cleaner'
  gem 'racksh'
end
