source 'https://rubygems.org'
ruby '3.2.2'

gem 'rake'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '7.0.4'

# Security updates
gem 'sprockets-rails', '~> 3'
gem "actionpack", "7.0.4"

# Load environment variables in development
gem 'dotenv-rails'

# MySQL the database for Active Record
gem 'mysql2', '0.5.6'

# Browserify
gem 'browserify-rails'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'

# Use haml for templates
gem 'haml-rails'

# Use Uglifier as compressor for JavaScript assets

# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'font-awesome-sass', '~> 6.4.0'

# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1'

gem 'devise', '~> 4.9'
gem 'carrierwave'
gem 'mini_magick'
gem 'cocoon'
gem 'recaptcha', require: 'recaptcha/rails' 
gem 'role_model'
gem 'delayed_job_active_record'
gem 'daemons'
gem 'braintree'
gem 'dkim'
gem 'simple_form', '~>5'

# Pdf creation
gem 'wkhtmltopdf-binary'
gem 'wicked_pdf'

gem 'gibbon' # Mailchimp API

# Application server
gem 'puma', '6.4.0'

gem 'letter_opener'

group :development do
  gem 'byebug'
  gem 'pry-rails'
  gem 'capistrano', '3.18.1'
  gem 'capistrano-rails'
  gem 'capistrano-bundler'
  gem 'capistrano-yarn'
  gem 'ed25519', '>= 1.2', '< 2.0'
  gem 'bcrypt_pbkdf', '>= 1.0', '< 2.0'
end

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_bot_rails'
  gem 'database_cleaner'
  gem 'racksh'
end

gem "terser", "~> 1.1"
