require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MainPagesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # MainPage. As you add validations to MainPage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MainPagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all main_pages as @main_pages" do
      main_page = MainPage.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:main_pages)).to eq([main_page])
    end
  end

  describe "GET #show" do
    it "assigns the requested main_page as @main_page" do
      main_page = MainPage.create! valid_attributes
      get :show, {id: main_page.to_param}, valid_session
      expect(assigns(:main_page)).to eq(main_page)
    end
  end

  describe "GET #new" do
    it "assigns a new main_page as @main_page" do
      get :new, {}, valid_session
      expect(assigns(:main_page)).to be_a_new(MainPage)
    end
  end

  describe "GET #edit" do
    it "assigns the requested main_page as @main_page" do
      main_page = MainPage.create! valid_attributes
      get :edit, {id: main_page.to_param}, valid_session
      expect(assigns(:main_page)).to eq(main_page)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new MainPage" do
        expect {
          post :create, {main_page: valid_attributes}, valid_session
        }.to change(MainPage, :count).by(1)
      end

      it "assigns a newly created main_page as @main_page" do
        post :create, {main_page: valid_attributes}, valid_session
        expect(assigns(:main_page)).to be_a(MainPage)
        expect(assigns(:main_page)).to be_persisted
      end

      it "redirects to the created main_page" do
        post :create, {main_page: valid_attributes}, valid_session
        expect(response).to redirect_to(MainPage.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved main_page as @main_page" do
        post :create, {main_page: invalid_attributes}, valid_session
        expect(assigns(:main_page)).to be_a_new(MainPage)
      end

      it "re-renders the 'new' template" do
        post :create, {main_page: invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested main_page" do
        main_page = MainPage.create! valid_attributes
        put :update, {id: main_page.to_param, main_page: new_attributes}, valid_session
        main_page.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested main_page as @main_page" do
        main_page = MainPage.create! valid_attributes
        put :update, {id: main_page.to_param, main_page: valid_attributes}, valid_session
        expect(assigns(:main_page)).to eq(main_page)
      end

      it "redirects to the main_page" do
        main_page = MainPage.create! valid_attributes
        put :update, {id: main_page.to_param, main_page: valid_attributes}, valid_session
        expect(response).to redirect_to(main_page)
      end
    end

    context "with invalid params" do
      it "assigns the main_page as @main_page" do
        main_page = MainPage.create! valid_attributes
        put :update, {id: main_page.to_param, main_page: invalid_attributes}, valid_session
        expect(assigns(:main_page)).to eq(main_page)
      end

      it "re-renders the 'edit' template" do
        main_page = MainPage.create! valid_attributes
        put :update, {id: main_page.to_param, main_page: invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested main_page" do
      main_page = MainPage.create! valid_attributes
      expect {
        delete :destroy, {id: main_page.to_param}, valid_session
      }.to change(MainPage, :count).by(-1)
    end

    it "redirects to the main_pages list" do
      main_page = MainPage.create! valid_attributes
      delete :destroy, {id: main_page.to_param}, valid_session
      expect(response).to redirect_to(main_pages_url)
    end
  end

end
