name: Build and Deploy

on:
  workflow_run:
    workflows: ["Build App"]
    types:
      - completed

jobs:
  # Deploy to Staging
  deploy-staging:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'staging' }}
    uses: ./.github/workflows/deploy-staging.yml
    env:
      SSH_PRIVATE_KEY: ${{ env.SSH_PRIVATE_KEY }} 

  # Deploy to Production
  deploy-production:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    uses: ./.github/workflows/deploy-production.yml
    env:
      SSH_PRIVATE_KEY: ${{ env.SSH_PRIVATE_KEY }}
      HOSTINGER_IP: ${{ env.HOSTINGER_IP }}"
      HOSTINGER_USER: ${{ env.HOSTINGER_USER }}"
