name: "Build App"
run-name: Build App
on:
  push:
    branches:
      - staging
      - main

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Check Out Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 1
 
      - name: Set ${{ github.ref_name }} branch
        run: |
          if [ "${{ github.ref_name }}" == "staging" ]; then
            echo "ENVIRONMENT=staging" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" == "main" ]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
          fi

      - name: Use the Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Rendezvous rails app image
        run: |
          docker build -f config/docker/Dockerfile -t ghcr.io/${{ github.repository_owner }}/rendezvous_rails_app:${{ github.sha }} ./rendezvous        

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/rendezvous_rails_app:${{ github.sha }}

      # Set secret as an environment variable for the next workflow
      - name: Pass SSH key to the next workflow
        run: |
          echo "SSH_PRIVATE_KEY=${{ secrets.RENDEZVOUS_REPO_SSH_KEY }}" >> $GITHUB_ENV
          echo "HOSTINGER_IP=${{ vars.HOSTINGER_IP }}" >> $GITHUB_ENV
          echo "HOSTINGER_USER=${{ vars.HOSTINGER_USER }}" >> $GITHUB_ENV


