name: Build and Deploy

on:
  workflow_run:
    workflows: ["Build App"]
    types:
      - success

jobs:
  # Deploy to Staging
  deploy-staging:
    if: ${{ github.event.workflow_run.head_branch == 'refs/heads/staging' }}
    uses: ./.github/workflows/deploy-staging.yml

  # Deploy to Production
  deploy-production:
    if: ${{ github.event.workflow_run.head_branch == 'refs/heads/main' }}
    uses: ./.github/workflows/deploy-production.yml
