name: Check Repo Branch vs Registry

on:
  workflow_call:
    inputs:
      repo:
        description: "GitHub repository (e.g., your-org/your-repo)"
        required: true
        type: string
      branch:
        description: "Branch to check"
        required: true
        type: string
      registry_image:
        description: "GHCR image name (e.g., ghcr.io/your-org/your-image:latest)"
        required: true
        type: string
    outputs:
      should_update:
        description: "True if registry update is needed"
        value: ${{ jobs.check-for-update.outputs.should_update }}

jobs:
  check-for-update:
    runs-on: ubuntu-latest
    outputs:
      should_update: ${{ steps.compare.outputs.should_update }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.branch }}
          fetch-depth: 2 

      - name: Get latest commit hash from branch
        id: branch_commit
        run: echo "commit_hash=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Get commit hash from GHCR image
        id: registry_commit
        run: |
          IMAGE_NAME=${{ inputs.registry_image }}
          DIGEST=$(docker manifest inspect $IMAGE_NAME | jq -r '.config.digest')
          echo "registry_digest=$DIGEST" >> $GITHUB_ENV

      - name: Get changed files
        id: changed_files
        run: |
          if [ -n "$registry_digest" ]; then
            PREV_COMMIT="$registry_digest"
          else
            PREV_COMMIT="$(git rev-parse HEAD~1)"
          fi

          echo "Comparing $PREV_COMMIT with HEAD"
          CHANGED_FILES=$(git diff --name-only $PREV_COMMIT HEAD)

          echo "Changed files:"
          echo "$CHANGED_FILES"

          # Check if any changed files are outside .github/
          should_update="false"
          for FILE in $CHANGED_FILES; do
            if [[ "$FILE" != .github/* ]]; then
              should_update="true"
              break
            fi
          done

          echo "should_update=$should_update" >> $GITHUB_OUTPUT
          fi