name: Copy Script File

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Copy script file'
        required: true
        default: 'staging'  # Default value if no input is provided
        type: string 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Check Out Repository
        uses: actions/checkout@v4
        with:
          ref: staging
          fetch-depth: 1
 

      - name: Set Staging Environment
        run: echo "ENVIRONMENT=staging" >> $GITHUB_ENV

      # Copy using SSH
      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{secrets.RENDEZVOUS_REPO_SSH_KEY}}

      # Upload the hostinger setup script
      - name: Copy the Hostinger setup script
        run: |
          scp -o StrictHostKeyChecking=no ./bin/setup_hostinger.sh ${{vars.HOSTINGER_USER}}@${{vars.HOSTINGER_IP}}:/home/webuser/bin

      - name: Check for the file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.HOSTINGER_IP }}
          username: ${{ vars.HOSTINGER_USER }}
          key: ${{ secrets.RENDEZVOUS_REPO_SSH_KEY }}
          script: ls ./bin

