name: Deploy Rendezvous Prod
run-name: Bulding and deploying Rendezvous production site

on:
  workflow_run:
    workflows: ["Build App"]
    types:
      - completed
    
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'  # Default value if no input is provided
        type: string 

jobs:
  deploy-app:  
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.head_branch == 'main' }}
    
    env:
      CONTAINER_NAME: "rendezvous-rails-app-prod"
      MAX_CHECKS: 10
      COUNT: 0
      STOPPED: true

    steps:
      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.RENDEZVOUS_REPO_SSH_KEY }}

      - name: Verify the evironment
        run: echo "The environment is $ENVIRONMENT"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.HOSTINGER_IP }}
          username: ${{ vars.HOSTINGER_USER }}
          key: ${{ secrets.RENDEZVOUS_REPO_SSH_KEY }}
          script: |
            if [ ! -d "/var/www/rendezvous-docker-prod" ]; then
              echo "    No repository directory - creating"
              mkdir -p /var/www/rendezvous-docker-prod
            fi
            cd /var/www/rendezvous-docker-prod
            echo "-- Pulling the latest Docker image from the registry --"
            docker pull ghcr.io/${{ github.repository_owner }}/rendezvous_rails_app:latest

            echo "-- Stopping the existing container --"
            docker compose down

            echo "-- Launching the new container with the latest image --"
            docker compose -f hostinger-compose.yml up -d

            echo "-- Installing JavaScript dependencies with Yarn inside the container --"
            docker exec rendezvous-rails-app-prod yarn install

            echo "-- Precompiling assets inside the container --"
            docker exec rendezvous-rails-app-prod rake assets:precompile

            echo "-- Restart the container"
            docker compose down
            docker compose -f hostinger-compose.yml up -d

            echo "-- Running migrations if needed --"
            if docker exec rendezvous-rails-app-prod bundle exec rails db:migrate:status | grep "down"; then
              echo "Pending migrations found. Running db:migrate..."
              docker exec rendezvous-rails-app-prod bundle exec rails db:migrate
            else
              echo "No pending migrations. Skipping db:migrate."
            fi
            
