name: Deploy Rendezvous Staging
run-name: Bulding and deploying Rendezvous staging site

on:  
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'staging'  # Default value if no input is provided
        type: string 

  deploy-app:  
    runs-on: ubuntu-latest
      env:
        CONTAINER_NAME: "rendezvous-rails-app-prod"
        MAX_CHECKS: 10
        COUNT: 0
        STOPPED: true

    steps:
      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.RENDEZVOUS_REPO_SSH_KEY }}

      # Upload the hostinger setup script
      # - name: Upload Hostinger setup script
      #   run: |
      #     scp -o StrictHostKeyChecking=no ./bin/setup_hostinger.sh ${{vars.HOSTINGER_USER}}@${{vars.HOSTINGER_IP}}:/home/webuser/bin

      - name: Debug the evironment
        run: echo "The environment is $ENVIRONMENT"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.HOSTINGER_IP }}
          username: ${{ vars.HOSTINGER_USER }}
          key: ${{ secrets.RENDEZVOUS_REPO_SSH_KEY }}
          script: |
            cd /var/www/rendezvous-docker-staging
            echo "-- Updating the git repository --"
            if [ ! -d ".git" ]; then
              echo "    Not a git repository, cloning and checking out"
              git clone https://github.com/${{ github.repository }} .
            else
              echo "    Repository found, pulling the latest changes"
              git pull origin staging
            fi
            echo "-- Checking out staging branch"
            git checkout staging
            echo "-- Installing JavaScript dependencies with Yarn --"
            docker exec rendezvous-rails-app-staging yarn install
            echo "-- Precompile assets"
            docker exec rendezvous-rails-app-staging rake assets:precompile
            echo "-- Bring down the site"
            docker compose -f hostinger-compose.yml down
            echo "-- Relaunch the site"
            docker compose -f hostinger-compose.yml up -d
                        echo "-- Running migrations if needed"
            if docker exec rendezvous-rails-app-staging bundle exec rails db:migrate:status | grep "down"; then
              echo "Pending migrations found. Running db:migrate..."
              docker exec rendezvous-rails-app-staging bundle exec rails db:migrate
            else
              echo "No pending migrations. Skipping db:migrate."
            fi
            
