name: Remote ssh command test
on: [workflow_dispatch]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ vars.HOSTINGER_IP }}
        username: ${{ vars.HOSTINGER_USER }}
        key: ${{ secrets.HOSTINGER_SSH_KEY }}
        script: pwd
